AWSTemplateFormatVersion: 2010-09-09
Description: Test template

Parameters:
  OperatorEmail: 
    Description: "Email address to notify when new logs are published."
    Type: String
    Default: mgk9530@gmail.com   

Resources:

###########
# CloudTrail
###########
  cloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties: 
      CloudWatchLogsLogGroupArn:
        Fn::GetAtt:
          - "logGroup"
          - "Arn"
      CloudWatchLogsRoleArn:
        Fn::GetAtt:
          - "IamRoleForCwLogsCloudTrail"
          - "Arn"
      EnableLogFileValidation: True
      EventSelectors: 
        - IncludeManagementEvents: True
      IncludeGlobalServiceEvents: True
      IsLogging: True
      IsMultiRegionTrail: True
      S3BucketName: !Ref s3fortrail
      SnsTopicName: 
        Fn::GetAtt:
          - Topic
          - TopicName
      TrailName: test-Trail

###############
# S3 bucket for CWT
################
  s3fortrail:
    Type: AWS::S3::Bucket
    Properties: {}

###############
# S3 policy for CWT
###############
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        !Ref s3fortrail
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              Fn::GetAtt:
                - s3fortrail
                - Arn
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource:
              Fn::Join:
                - ""
                -
                  - Fn::GetAtt:
                      - "s3fortrail"
                      - "Arn"
                  - "/AWSLogs/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"

############
#Topic for CWT
############
  Topic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - 
          Endpoint: 
            Ref: OperatorEmail
          Protocol: email

##################
# Topic-policy for CLT
##################
  TopicPolicy: 
    Type: AWS::SNS::TopicPolicy
    Properties: 
      Topics: 
        - Ref: Topic
      PolicyDocument: 
        Version: "2008-10-17"
        Statement: 
          - 
            Sid: "AWSCloudTrailSNSPolicy"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Resource: "*"
            Action: "SNS:Publish"

         
###########
# Loggroup
###########
  logGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: logGroupForTrail
      RetentionInDays: 1

###############
# IAM Role for CWT
###############
  IamRoleForCwLogsCloudTrail:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "allow-access-to-cw-logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"


       
