AWSTemplateFormatVersion: 2010-09-09
Description: Bastion Host template


Parameters:
  ExportStackName:
    Description: The name of the stack that exports the values
    Type: String

  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Select KeyPair

  BastionAMIID:
    Type: String
    Default: image id 




Resources:

###########
# Bastion
##########

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      ImageId: !Ref BastionAMIID
      SubnetId: 
        Fn::ImportValue: !Sub '${ExportStackName}-PublicSubnet1'
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: Bastion Host


############
# Bastion SG
############

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Bastion
      GroupDescription: Open Port 22 for ssh
      VpcId:
        Fn::ImportValue: !Sub '${ExportStackName}-LabVPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Bastion


###########
# IAM Role for Instance
###########

  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: Ec2FullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'ec2:*'
                Resource: '*'


###########
# Instance Profile
###########

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref Ec2Role]
      InstanceProfileName: Ec2Role



Outputs:
  BastionPublicDns:
    Value: !GetAtt BastionInstance.PublicDnsName
    Description: Bastion Dns Name
    Export:
      Name: !Sub ${AWS::StackName}-BastionPublicDns