AWSTemplateFormatVersion: 2010-09-09
Description: this template is for DR of region1, region2


Parameters:

  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Select KeyPair

  UbuntuAMIID:
    Type: String
    Default: ami-092faff259afb9a26

Resources:

###########
# DR Instance
###########

  DRInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      ImageId: !Ref UbuntuAMIID
      SecurityGroupIds:
        - !Ref DRSecurityGroup
      IamInstanceProfile: !Ref DRInstanceProfile
      Tags:
        - Key: Name
          Value: DR
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          ##########################
          #install aws cli2
          ##########################
          apt update       
          apt install -y awscli
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          apt install unzip  
          unzip awscliv2.zip
          sudo ./aws/install

          ##########################
          #Config to Japan Osaka Region /ap-northeast-3/
          ##########################

          ##########################
          #create VPC stack on ap-northeast-3
          ##########################
          aws cloudformation create-stack --stack-name myVPC --template-url https://drtemplate.s3.ap-northeast-2.amazonaws.com/Region2/1.VPC.yaml --parameters ParameterKey=LabVpcCidr,ParameterValue=192.168.0.0/16 ParameterKey=PublicSubnet1Cidr,ParameterValue=192.168.10.0/24 ParameterKey=PublicSubnet2Cidr,ParameterValue=192.168.30.0/24 ParameterKey=PrivateSubnet1Cidr,ParameterValue=192.168.20.0/24 ParameterKey=PrivateSubnet2Cidr,ParameterValue=192.168.40.0/24  --region ap-northeast-3

          ##########################
          #wait vpc stack
          ##########################
          aws cloudformation wait stack-create-complete --stack-name myVPC --region ap-northeast-3

          ##########################
          #create rds stack on ap-northeast-3          
          ##########################
          aws cloudformation create-stack --stack-name myRDS --template-url https://drtemplate.s3.ap-northeast-2.amazonaws.com/Region2/2.RDS_template.yaml --parameters ParameterKey=ExportStackName,ParameterValue=myVPC ParameterKey=DBUsername,ParameterValue=admin ParameterKey=DBPassword,ParameterValue=123456789 ParameterKey=DBInstanceIdentifier,ParameterValue=dbinstance-ap-northeast-3 --region ap-northeast-3

          ##########################
          #wait rds stack
          ##########################
          aws cloudformation wait stack-create-complete --stack-name myRDS --region ap-northeast-3

          ##########################
          #create bastion stack on ap-northeast-2
          ##########################
          aws cloudformation create-stack --stack-name myBastion --template-url https://drtemplate.s3.ap-northeast-2.amazonaws.com/Region2/3.Bastion.yaml --parameters ParameterKey=ExportStackName,ParameterValue=myVPC ParameterKey=KeyName,ParameterValue=jpAdmin ParameterKey=BastionAMIID,ParameterValue=ami-092faff259afb9a26 --region ap-northeast-3 --capabilities CAPABILITY_NAMED_IAM

          ##########################
          #wait bastion stack
          ##########################
          aws cloudformation wait stack-create-complete --stack-name myBastion --region ap-northeast-3

          ##########################
          #JpBastionId is Output value of Bastion's stack
          ##########################
          JpBastionId=`aws cloudformation describe-stacks --query 'Stacks[].Outputs[?OutputKey==\`BastionId\`].OutputValue' --output=text --region=ap-northeast-3`

          ##########################
          #wait bastion instance's status
          ##########################
          aws ec2 wait instance-status-ok --instance-ids $JpBastionId --region ap-northeast-3

          ##########################
          #create nat instance stack on ap-northeast-3
          ##########################
          aws cloudformation create-stack --stack-name myNAT --template-url https://drtemplate.s3.ap-northeast-2.amazonaws.com/Region2/4.NAT.yaml --parameters ParameterKey=ExportStackName,ParameterValue=myVPC ParameterKey=KeyName,ParameterValue=jpAdmin ParameterKey=UbuntuAMI,ParameterValue=ami-092faff259afb9a26 --region ap-northeast-3 --capabilities CAPABILITY_NAMED_IAM

          ##########################
          #wait nat instance stack
          ##########################
          aws cloudformation wait stack-create-complete --stack-name myNAT --region ap-northeast-3

          ##########################
          #create GoldenAMI instance stack on ap-northeast-3
          ##########################
          aws cloudformation create-stack --stack-name myGoldenAMI --template-url https://drtemplate.s3.ap-northeast-2.amazonaws.com/Region2/5.Golden_AMI.yaml --parameters ParameterKey=ExportStackName,ParameterValue=myVPC ParameterKey=KeyName,ParameterValue=jpAdmin ParameterKey=GoldenAMIID,ParameterValue=ami-092faff259afb9a26 --region ap-northeast-3 --capabilities CAPABILITY_NAMED_IAM

          ##########################
          #wait GoldenAMI stack
          ##########################
          aws cloudformation wait stack-create-complete --stack-name myGoldenAMI --region ap-northeast-3

          ##########################
          #HzId is HostZoneId of suyeonshoes.click
          ##########################
          HzId=`aws route53 list-hosted-zones-by-name --dns-name "suyeonshoes.click." --query HostedZones[].Id --output=text`

          ##########################
          #GoldenAMIId is Output value of GoldenAMIId's stack
          ##########################
          GoldenAMIId=`aws cloudformation describe-stacks --query 'Stacks[].Outputs[?OutputKey==\`GoldenAMIId\`].OutputValue' --output=text --region=ap-northeast-3`

          ##########################
          #wait GoldenAMIId instance's status
          ##########################
          aws ec2 wait instance-status-ok --instance-ids $GoldenAMIId --region ap-northeast-3

          ##########################
          #wait myAS stack
          ##########################
          aws cloudformation wait stack-create-complete --stack-name myAS --region ap-northeast-3


          ##########################
          #JpALBDNs and JpALBHz is output value of ap-norhteast-3's myAS stack
          ##########################
          JpALBDns=`aws cloudformation describe-stacks --query 'Stacks[].Outputs[?OutputKey==\`ALBDns\`].OutputValue' --output=text --region=ap-northeast-3`
          JpALBHz=`aws cloudformation describe-stacks --query 'Stacks[].Outputs[?OutputKey==\`ALBHz\`].OutputValue' --output=text --region=ap-northeast-3`

          ##########################
          #create Route53 instance stack on ap-northeast-3
          ##########################
          aws cloudformation create-stack --stack-name myRoute53 --template-url https://drtemplate.s3.ap-northeast-2.amazonaws.com/Region2/6.Route53_Region2.yaml --parameters ParameterKey=ExportStackName,ParameterValue=myVPC ParameterKey=JpALBDns,ParameterValue=$JpALBDns ParameterKey=JpALBHz,ParameterValue=$JpALBHz ParameterKey=HzId,ParameterValue=$HzId --region ap-northeast-3 --capabilities CAPABILITY_NAMED_IAM


############
# DRSecurityGroup
############

  DRSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: DRSecurityGroup
      GroupDescription: Open Port 22 , 80 for ssh
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: DRSecurityGroup


###########
# IAM Role for Instance
###########

  jpDRRoles:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: FullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'rds:*'
                Resource: '*'
              - Effect: Allow
                Action: 'ec2:*'
                Resource: '*'
              - Effect: Allow
                Action: 's3:*'
                Resource: '*'
              - Effect: Allow
                Action: 'cloudformation:*'
                Resource: '*'
              - Effect: Allow
                Action: 'ssm:*'
                Resource: '*'
              - Effect: Allow
                Action: 'elasticloadbalancing:*'
                Resource: '*'
              - Effect: Allow
                Action: 'iam:*'
                Resource: '*'
              - Effect: Allow
                Action: 'autoscaling:*'
                Resource: '*'
              - Effect: Allow
                Action: 'route53:*'
                Resource: '*'
              - Effect: Allow
                Action: 'sns:*'
                Resource: '*'
              - Effect: Allow
                Action: 'sts:*'
                Resource: '*'
              - Effect: Allow
                Action: 'imagebuilder:*'
                Resource: '*'
              - Effect: Allow
                Action: 'lambda:*'
                Resource: '*'
###########
# Instance Profile
###########

  DRInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref jpDRRoles]
      InstanceProfileName: jpDRRoles




