AWSTemplateFormatVersion: 2010-09-09
Description: peers the VPCs
Parameters:

  ExportStackName:
    Description: The name of the stack that exports the values
    Type: String

  PeerVpcId:
    Description: accepter VPC ID
    Type: String

  PeerRegion: 
    Description: accepter VPC Region
    Type: String

Resources:
 
  myVPCPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId:
        Fn::ImportValue: !Sub '${ExportStackName}-LabVPC'

      PeerVpcId: !Ref PeerVpcId
      PeerRegion: !Ref PeerRegion
      Tags:
        - Key: Name
          Value: KR JP Peering


Outputs:
  PeeringId:
    Value: !Ref myVPCPeeringConnection
    Description: PeeringId
    Export:
      Name: !Sub ${AWS::StackName}-PeeringId